apiVersion: apps/v1
kind: Deployment
metadata:
  name: catternauts
spec:
  template:
    metadata:
      labels:
        name: catternauts
    spec:
      containers:
        - name: catternauts
          images: dwilliamscfexamplevotingapp/catternauts:latest
