apiVersion: apps/v1
kind: Deployment
metadata:
  name: catternauts
  namespace: catternauts
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catternauts
  template:
    metadata:
      labels:
        name: catternauts
        app: catternauts
    spec:
      containers:
        - name: catternauts
          images: dwilliamscfexamplevotingapp/catternauts:latest
          env:
            - name: REDIS_SERVER_HOSTNAME
              value: spin-redis.spinnaker
