version: '1.0'
stages:
  - build
  - deploy
  #- "pull request"
  #- staging
  #- production
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/cicd-example-app'
    revision: '${{CF_REVISION}}'
    git: github
  BuildImage:
    title: Building Image
    type: build
    stage: build
    image_name: ${{DOCKER_ORGANIZATION}}/catternauts
    working_directory: ./
    dockerfile: Dockerfile
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
  UnitTest:
    title: Unit Tests
    image: '${{BuildImage}}'
    stage: build
    commands:
      - pip install -r requirements_test.txt
      - coverage run --include app.py -m py.test
  Deploy:
    title: Deploy PR image to Kubernetes
    type: deploy
    stage: deploy
    cluster: '${{KUBE_CONTEXT}}'
    kind: kubernetes
    namespace: '${{KUBE_NAMESPACE}}'
    service: 'catternauts'
    candidate:
      image: '${{DOCKER_ORGANIZATION}}/catternauts:${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
      registry: example-voting-app

