version: '1.0'
stages:
  - build
  #- "pull request"
  #- staging
  #- production
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/cicd-example-app'
    revision: '${{CF_REVISION}}'
    git: github
  BuildingMicroServices:
    type: parallel
    stage: build
    steps:
      BuildResultImage:
        title: Building Result Image
        type: build
        image_name: ${{DOCKER_ORGANIZATION}}/catternauts
        working_directory: ./
        dockerfile: Dockerfile
        tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
      Deploy:
        title: Deploy PR image to Kubernetes
        type: deploy
        cluster: '${{KUBE_CONTEXT}}'
        kind: kubernetes
        namespace: '${{KUBE_NAMESPACE}}'
        service: 'catternauts'
        candidate:
          image: '${{DOCKER_ORGANIZATION}}/catternauts:${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'

